version: "3"
services:
    node-app:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - MONGO_USER=omerarafat
            - MONGO_PASSWORD=omerarafat
            - SESSION_SECRET=secret
        command: npm run dev
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=omerarafat
            - MONGO_INITDB_ROOT_PASSWORD=omerarafat